version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=MusicalDictate
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postrgresql/data
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
  studentapi:
    image: musicaldictateregistry.azurecr.io/studentapi
    ports:
      - "7001:443"
      - "5001:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=http://localhost:3010"
  teacherapi:
    image: musicaldictateregistry.azurecr.io/teacherapi
    ports:
      - "7002:443"
      - "5002:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password;IncludeErrorDetail=true"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=http://localhost:3001"
  webapi:
    image: musicaldictateregistry.azurecr.io/webapi
    ports:
      - "7003:443"
      - "5003:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password;IncludeErrorDetail=true"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=http://localhost:3010;http://localhost:3001"
  simplegrader:
    image: musicaldictateregistry.azurecr.io/simplegrader
    ports:
      - "7004:443"
      - "5004:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password;IncludeErrorDetail=true"
      - "Endpoints__WebApi=http://webapi"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
    depends_on:
      - webapi
  studentui:
    image: musicaldictateregistry.azurecr.io/studentui
    ports:
      - "3010:3010"
    environment:
      - REACT_APP_STUDENT_API=http://localhost:5001
    depends_on:
      - studentapi
  teacherui:
    image: musicaldictateregistry.azurecr.io/teacherui
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_TEACHER_API=http://localhost:5002
    depends_on:
      - teacherapi
volumes:
  db:
    driver: local
