version: '3.4'

networks:
  backend: #private
  frontend: #public

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=MusicalDictate
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postrgresql/data
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  musicaldictateapi:
    image: musicaldictateregistry.azurecr.io/musicaldictateapi
    environment:
      - "ASPNETCORE_URLS=http://+:80"
    ports:
      - "80:80"
    depends_on:
      - studentapi
      - teacherapi
      - webapi
      - studentui
      - teacherui
    networks:
      - backend
      - frontend
  studentapi:
    image: musicaldictateregistry.azurecr.io/studentapi
    ports:
      - "7001:443"
      - "5001:80"
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=https://musical-dictate-student.web.app"
    networks:
      - backend
  teacherapi:
    image: musicaldictateregistry.azurecr.io/teacherapi
    ports:
      - "7002:443"
      - "5002:80"
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=https://musical-dictate-teacher.web.app"
    networks:
      - backend
  webapi:
    image: musicaldictateregistry.azurecr.io/webapi
    ports:
      - "7003:443"
      - "5003:80"
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=http://localhost:3010;http://localhost:3001"
    networks:
      - backend
  simplegrader:
    image: musicaldictateregistry.azurecr.io/simplegrader
    ports:
      - "7004:443"
      - "5004:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password"
      - "Endpoints__WebApi=http://webapi"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
    depends_on:
      - webapi
    networks:
      - backend
volumes:
  db:
    driver: local
