version: '3.4'

networks:
  backend: #private
  frontend: #public

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=MusicalDictate
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postrgresql/data
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  musicaldictateapi:
    image: musicaldictateapi
    build:
      context: Backend/MusicalDictate/
      dockerfile: src/ApiGateway/Dockerfile
    environment:
      - "ASPNETCORE_URLS=http://+:80"
    ports:
      - "5000:80"
    depends_on:
      - studentapi
      - teacherapi
      - webapi
      - studentui
      - teacherui
    networks:
      - backend
      - frontend
  studentapi:
    image: studentapi
    build:
      context: Backend/MusicalDictate/
      dockerfile: src/StudentApi/Dockerfile
    ports:
      - "7001:443"
      - "5001:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=http://localhost:3010"
    depends_on:
      - rabbitmq
    networks:
      - backend
  teacherapi:
    image: teacherapi
    build:
      context: Backend/MusicalDictate/
      dockerfile: src/TeacherApi/Dockerfile
    ports:
      - "7002:443"
      - "5002:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password;IncludeErrorDetail=true"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=http://localhost:3001"
    depends_on:
      - rabbitmq
    networks:
      - backend
  webapi:
    image: webapi
    build:
      context: Backend/MusicalDictate/
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "7003:443"
      - "5003:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password;IncludeErrorDetail=true"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
      - "Cors__AllowedOrigins=http://localhost:3010;http://localhost:3001"
    depends_on:
      - rabbitmq
    networks:
      - backend
  simplegrader:
    image: simplegrader
    build:
      context: Backend/MusicalDictate/
      dockerfile: src/SimpleGrader/Dockerfile
    ports:
      - "7004:443"
      - "5004:80"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "ConnectionStrings__DefaultConnection=Host=db,1433;Database=MusicalDictate;Username=user;Password=password;IncludeErrorDetail=true"
      - "Endpoints__WebApi=http://webapi"
      - "RabbitMq__Host=rabbitmq"
      - "RabbitMq__Username=guest"
      - "RabbitMq__Password=guest"
    depends_on:
      - rabbitmq
      - webapi
    networks:
      - backend
  studentui:
    image: studentui
    build:
      context: Frontend/Student
      dockerfile: ./Dockerfile
    ports:
      - "3010:3010"
    environment:
      - REACT_APP_STUDENT_API=http://localhost:5000/student
    depends_on:
      - studentapi
    networks:
      - frontend
  teacherui:
    image: teacherui
    build:
      context: Frontend/Teacher
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_TEACHER_API=http://localhost:5000/teacher
    depends_on:
      - teacherapi
    networks:
      - frontend
volumes:
  db:
    driver: local
